### ISSUE TITLE
Polymer's `async` returns `undefined` if the extension is enabled.

### ISSUE THREAD

**Issue by trading-peter** [PolymerLabs/polydev#17]
Suddenly all return values from `Polymer.Base.async` were `undefined`. As soon as I disabled the polydev extension, the return values were all fine again.

**With polydev enabled**

``` js
ready: function() {
  var job = this.async(function() { console.log('did it'); }, 1000);
  console.log(job); // -> undefined
}
```

**With polydev disabled**

``` js
ready: function() {
  var job = this.async(function() { console.log('did it'); }, 1000);
  console.log(job); // -> -3   as expected
}
```

Is polydev maybe hungry for the return values ;)

**Comment by justinfagnani** [comment]
Fixed by https://github.com/PolymerLabs/element-zones/pull/6

**Comment by justinfagnani** [comment]
The updated package is on the Chrome Web Store now. Thanks for the report @pkaske !

**Comment by trading-peter** [comment]
You're welcome. Thanks for the quick fix!
