### ISSUE TITLE
polydev causes more issues in paper-dropdown 

### ISSUE THREAD

**Issue by srikkbhat** [PolymerLabs/polydev#23]
Open the below link in chrome with polydev enabled

http://output.jsbin.com/curike
1. When I open the dropdown, I see a message "Uncaught TypeError: Cannot read property 'toString' of null   polydev/vendor/zone-microtask.js:973".
2. When I try to close the dropdown by clicking outside, it does not close.
3. When I select a value, I get another message "Uncaught TypeError: Cannot read property '_bound' of null polydev/vendor/zone-microtask.js:995"

The issues disappear when I disabled polydev.

**Comment by bsinc** [comment]
I've been getting the same error, using an iron-dropdown. And same solution for me, disabling the polydev extension cleared all the issues.

**Comment by lephuhai** [comment]
I have the same issue.

**Comment by githubGabriela** [comment]
Did anyone found a solution for this bug (besides disabling Polydev) ?

**Comment by rictic** [comment]
This should be fixed in v0.0.7 which was just merged in #35 and published. Please file a new issue if you see any more problems like this.
