### ISSUE TITLE
google search broken

### ISSUE THREAD

**Issue by rbellens** [PolymerLabs/polydev#26]
When polydev is enabled, google search is broken. It still works when entering a query in the address bar, but when changing the query in the search field of the page and pressing enter, the search results become and remain disabled.
The following error message is shown in the console:

```
polydev/vendor/zone-microtask.js:123 Uncaught TypeError: Cannot read property 'elements' of undefined
```

**Comment by ebidel** [comment]
It's recommended to use polydev in a clean profile in chrome because of
its pervasiveness.
