### ISSUE TITLE
polydev causing paper-dialog to fail.

### ISSUE THREAD

**Issue by ranjeet-choudhary** [PolymerLabs/polydev#27]
Uncaught TypeError: Cannot read property 'toString' of null

below is the code giving the issue:
handler is null.

function patchEventTargetMethods(obj) {
  var addDelegate = obj.addEventListener;
  obj.addEventListener = function (eventName, handler) {
    var fn;
    //Ignore special listeners of IE11 & Edge dev tools, see https://github.com/angular/zone.js/issues/150
    if (handler.toString() !== "[object FunctionWrapper]") {

**Comment by rictic** [comment]
This should be fixed in v0.0.7 which was just merged in #35 and published. Please file a new issue if you see any more problems like this.
