### ISSUE TITLE
Polydev breaks x-tag based websites

### ISSUE THREAD

**Issue by Granze** [PolymerLabs/polydev#28]
Just noticed this visiting http://x-tag.github.io/

![screen shot 2015-11-25 at 4 27 58 pm](https://cloud.githubusercontent.com/assets/1193298/11401176/9160d054-9391-11e5-8c16-4d4b1df90998.png)

**Comment by yordis** [comment]
Indeed :+1:

**Comment by GeoloeG-IsT** [comment]
on purpose? :D

**Comment by ebidel** [comment]
See https://github.com/PolymerLabs/polydev/issues/26#issuecomment-158975027
