### ISSUE TITLE
Synchronous XHR is not allowed anymore. Warning issued in console..

### ISSUE THREAD

**Issue by lucyllewy** [PolymerLabs/polydev#29]
warning as follows:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

Specifically, this is about line 52 in src/content-script.js

(Stable Chrome channel, version 47.0.2526.80 with PolyDev version 0.0.6 from Chrome Webstore)

**Comment by justinfagnani** [comment]
This is working as intended. Sync XHR is the only way I know of to get the script content that needs to be injected before any other scripts.

**Comment by lucyllewy** [comment]
You say that it's working as intended, but what happens when the deprecation is followed-up and becomes "synchronous xhr has been removed"?

**Comment by justinfagnani** [comment]
Then we'll have to search for another option - maybe there will be a sync filesystem API by then. Sync XHR is used by too many pages to actually be removed though.
