### ISSUE TITLE
Only inject zone.js if we are looking at a polymer app / inspecting 🔍

### ISSUE THREAD

**Issue by samccone** [PolymerLabs/polydev#3]
Or something like this... zone.js breaks quite a few sites ATM (like google)
Would be nice if this plugin did not break other sites :wink: 

I like the approach we used here https://github.com/marionettejs/marionette.inspector
where you have to manually opt in to running the script 

we then kinda hack into the guts of backbone and marionette and reload the page

cc @jasonlaster prob will have more insight on this for us :clap:

**Comment by justinfagnani** [comment]
The gating issue for this is whether or not we can synchronously retrieve a value to control whether we inject the script into the target tab. Maybe localStorage will help here.

**Comment by rictic** [comment]
As of v0.0.7 we no longer inject zone.js. We now load far les code, causing far less impact on pages.
