### ISSUE TITLE
breaks Google Play Music

### ISSUE THREAD

**Issue by jokeyrhyme** [PolymerLabs/polydev#30]
When I have this extension enabled, the search bar at the top of the page refuses to actually perform searches (although accepts search terms, etc), and the spinning activity indicator is perpetually visible (even when nothing should be happening).

Uninstalling / disabling this extension restores expected behaviour in Google Play Music.

**Comment by ebidel** [comment]
Polydev should be installed in a fresh chrome profile or disabled when you're not using it. See https://github.com/PolymerLabs/polydev#installation.

**Comment by samccone** [comment]
since this is on the extension "store" it is easy for people to miss these instructions
