### ISSUE TITLE
PolyDev Chrome Extension Broken?

### ISSUE THREAD

**Issue by barnomics** [PolymerLabs/polydev#34]
This plugin used to be quite handy, but now it no longer seems to work with sites that I was successful debugging before. 

Steps to reproduce:  
1. Enable extension
2. Visit https://elements.polymer-project.org/ or polymer-project.org.  Open console log and you'll see a bunch of _toString and _bound related errors .

**Comment by 43081j** [comment]
I get this too, the `ready()` callbacks don't seem to be firing so a huge amount of properties and such are not initialised correctly.

**Comment by rictic** [comment]
This should be fixed in v0.0.7 which was just merged in #35 and published. Please file a new issue if you see any more problems like this.

We did change the design significantly, but it should be for the better, as it's more integrated into the rest of devtools' performance monitoring systems.
