### ISSUE TITLE
Time visualization style

### ISSUE THREAD

**Issue by samccone** [PolymerLabs/polydev#5]
**i.e**

![screen shot 2015-09-09 at 11 08 12 pm](https://cloud.githubusercontent.com/assets/883126/9781322/ce49993c-5747-11e5-9d64-acee8e0bb5dd.png)

I think this will make it a bunch easier for humans to understand the numbers

---

I defer to @paulirish for some sage knowledge on the best way to present this one :bow:

**Comment by addyosmani** [comment]
How well would that look in a condensed mode like dock-to-right?

**Comment by samccone** [comment]
Ha probably pretty poor :/

**Comment by paulirish** [comment]
actually, given that default width is 555px and the panel has all of that space, it should work just fine.

**Comment by paulirish** [comment]
here's a few screenshots of this UI pattern in action: 

![image](https://cloud.githubusercontent.com/assets/39191/9792500/3944d34e-5795-11e5-8144-bd61edcb0964.png)

i prefer the bars sharing the same column as the text, but some do it separately:

![image](https://cloud.githubusercontent.com/assets/39191/9792522/619c0ef2-5795-11e5-8bcb-18ee68a65bf7.png)
![image](https://cloud.githubusercontent.com/assets/39191/9792559/9bd5c176-5795-11e5-870f-17fbf72544bd.png)

**Comment by samccone** [comment]
![screen shot 2015-09-10 at 4 26 01 pm](https://cloud.githubusercontent.com/assets/883126/9803622/4ef075d8-57d9-11e5-9b4f-c02dda1871b9.png)

and now we are in the cool club

**Comment by samccone** [comment]
![screen shot 2015-09-10 at 5 29 57 pm](https://cloud.githubusercontent.com/assets/883126/9804473/c1910f36-57e2-11e5-8477-e3ef679908cc.png)

After a bit more work @paulirish and I ended up on this approach

**Comment by justinfagnani** [comment]
I merged the column width PR, and changed the to left aligned, but will leave this open to discuss the idea visualization. I kind of like a stacked bar chat, but like the current layout as well.

**Comment by justinfagnani** [comment]
I'm going to close this for now. New UI ideas can be proposed in new issues.
