### ISSUE TITLE
polymer summit

### ISSUE THREAD

**Issue by paulirish** [PolymerLabs/polydev#6]
Who is showing this at polymer summit!? I will probably use it myself.. :)

**Comment by paulirish** [comment]
I present at the end so I imagine it will have been shown by then? @ebidel will you be showing it? 

If not I'll want to talk to you @justinfagnani to make sure I introduce and debut it well. :)

**Comment by ebidel** [comment]
Yea, I have a slide that mentions it.

**Comment by paulirish** [comment]
Dope. I'll be showing it in action so i'll just continue where you left off.  sgtm!

**Comment by ebidel** [comment]
Actually, if you're definitely going to use it, I may forgo mentioning it.
Running out of time on this one :)
If anything, I'll be like, "Irish will take care of you".

**Comment by paulirish** [comment]
wfm!​

**Comment by justinfagnani** [comment]
@paulirish let me know if you have any questions about how this works. The tracking async tasks and associating back to elements bit is interesting, to me anyway.

Also, I might try to land a feature or two soon. I know it's coming in hot :)
